### ISSUE TITLE
Shattering

### ISSUE THREAD

**Issue by raphaellaude** [districtr/districtr-v2#13]

**Comment by mariogiampieri** [comment]
Reflecting on this and the paint by county functionality- I think it would be worth testing precomputing vtd and county membership of blocks on ingestion / tile creation so that we can paint by county _and_ shatter based on IDs instead of using turf in the browser. 

If we were to use turf to shatter, I imagine we would:
- get VTD geom / id based on user selection
- use `queryRenderedFeatures` and the like a la current `getFeaturesIntersectingCounties` to use turf to select features that are members
- set an expression to show those features

If we used an ID, I'd image we'd:
- get VTD geom / id based on user selection
- use `queryRenderedFeatures`, loop through features to see if `vtdId` matches the search feature
- set an expression to show those features

Thoughts? Is this silly? I imagine that if this is performant we could also test in on the PaintByCounty (although the actual paint part does seem snippy!)

**Comment by raphaellaude** [comment]
> Reflecting on this and the paint by county functionality- I think it would be worth testing precomputing vtd and county membership of blocks on ingestion

I think we should 100% compute block -> parent memberships via the CLI and do no heavy geometry operations like calculating intersections in the browser (i.e. not shatter in browser). 

I'm 50/50 on adding **county membership to tiles**. TLDR / train-of-thought thoughts:

We should weigh the benefits of a simpler implementation (+1 for adding the county FIPS attribute to tiles) vs. more flexible† (+1 for computing in browser) and perf–the tile rendering is already getting a tad slow on the initial load, esp. for block layers, though you could easily imagine that a fullproof implementation with turf in the browser would get much hairier and less performant, not to mention bundle size concerns.

Re: implementation if we add county FIPS to tilesets:

> If we used an ID, I'd image we'd:
> - get VTD geom / id based on user selection
> - use queryRenderedFeatures, loop through features to see if vtdId matches the search feature
> - set an expression to show those features

A much simpler implementation is to do what Districtr v1 does and use `querySourceFeatures` using a mapbox expression to query features matching the county FIPS code.

† More flexible because the function is actually intersection layer agnostic. We could paint by Places, VTDs (e.g. if we had a block layer), arbitrary geo etc. using this implementation.

**Comment by raphaellaude** [comment]
Some adjustments to the above based on a discussion with @bailliekova:

- **Loading**
    - Let's load each GerryDB separately but generate views in Postgres of the unioned child and parent layers.
    - This should allow for more modularity with tables / less data duplication / be easier to understand.
    - This view will have a constrained schema consisting of the shared columns between parent and child tables.

> 5. Insert two records to GerryDB layer metadata table (new table 📑)
- Instead this proposed GerryDB layer metadata model, let's create a new model `DistrictrMap` (better name?).
    - This model will sit between the GerryDB views and the FE and can contain other important info like the map name, description, GerryDB view name (whether single layer or unioned views view), parent tiles layer name, child tiles layer name, state, number of districts supported by a map, etc. i.e. stuff that doesn't belong to a GerryDB view but is 1-1 with the map a user is drawing.
    - An advantage of this system is it becomes much easier to create and update the constituent parts of a `DistrictrMap` in isolation and assemble the map attributes later (or update them). Right now, by contrast, it is possible for the GerryDB table to be missing a tile path. This incomplete state can lead to issues.

**Comment by raphaellaude** [comment]
Since we don't expect the UNION'ed tables to be changing at all, we can materialize them and create indices over path.
